name: record_on_calendar
description: Starts sound recording based on an ical link.
version: 0.0.1

environment:
  sdk: '>=2.16.1 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
dependencies: 
  archive: ^3.2.2
  console: ^4.1.0
  http: ^0.13.4
  icalendar_parser: ^1.0.1
