name: record_on_calendar
description: Record multitrack audio automatically according to iCal calendar events.
# Also change in utils/globals.dart
version: 4.0.2

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  archive: ^3.2.2
  console: ^4.1.0
  ffmpeg_cli: ^0.1.0
  http: ^0.13.4
  icalendar_parser: ^1.0.1
  mailer: ^5.1.0
  rrule: ^0.2.10
  yaml: ^3.1.1
